### ISSUE TITLE
 TypeError: Cannot read property 'replace' of undefined (path separator checks breaking on Windows)

### ISSUE THREAD

**Issue by anlexN** [ProjectEvergreen/greenwood#600] opened 2021-05-10 06:15 UTC
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
![image](https://user-images.githubusercontent.com/8686739/117613901-247a3200-b19a-11eb-96bd-9d4dfd808957.png)

## Details
Initial report captured [below in comments](https://github.com/ProjectEvergreen/greenwood/issues/600#issuecomment-842529912)

> The main issue is that when we map URLs to paths [like in **plugin-standard-html**](https://github.com/ProjectEvergreen/greenwood/blob/v0.12.2/packages/cli/src/plugins/resource/plugin-standard-html.js#L234) we do checks like this
> ```js
> const barePath = relativeUrl.endsWith('/')      
>  ? ...
>  : ...
> ```
>
> This will fail on Windows because Windows uses `\` as a path separator, not `/`, and so path look like this in Windows
> ```sh
> C:\Users\IEUser\Workspace\greenwood-getting-started\src\
> ```
>
> as opposed to this on Linux / macOS
> ```sh
> /Users/owenbuckley/Workspace/greenwood-getting-started/src
> ```

**Comment by thescientist13** [comment] 2021-05-10 13:11
Hey @anlexN , thanks for reaching out and reporting this.

I have enounctemed this a couple times myself and the root cause turned out to be that my HTML was invalid, usually because of a missing closing tag.  Can you check your content (page / templates) for anything that might be like that?

If that doesn't help or you're not able to resolve it, please feel free to provide a sample repo with your reproduction and I will be happy to take a look and review.  👍 

----

That advice aside, I do recognize for something as likely as common as some invalid HTML that would occur during normal development, it would be good for the project to find a good way to handle this when [parsing the HTML](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/plugins/resource/plugin-standard-html.js#L58) so at least we can print out a better message or other indicator to the user what might be the root cause.  

Once I help you with this issue, I think then it would be a good time for us to look into that.  🔍

**Comment by anlexN** [comment] 2021-05-11 00:39
[tutorial.zip](https://github.com/ProjectEvergreen/greenwood/files/6455677/tutorial.zip)
@thescientist13 please fix it.

**Comment by anlexN** [comment] 2021-05-12 01:26
i do, but still is wrong. i wait for you.

**Comment by thescientist13** [comment] 2021-05-17 18:12
Hey @anlexN , just wanted to give you an update that I was able to reproduce the issue in the main **greenwood-getting-started** repository, just had to spin up Windows in a VM first but I have good news.  I have identified the root cause and I should be able to get a fix up and published in a couple days for you.  (more info below 👇 )

Thanks for your report and trying out our project, I will update the issue description as well momentarily and get a PR up soon.

----

The main issue is that when we map URLs to paths [like in **plugin-standard-html**](https://github.com/ProjectEvergreen/greenwood/blob/v0.12.2/packages/cli/src/plugins/resource/plugin-standard-html.js#L234) we do checks like this
```js
const barePath = relativeUrl.endsWith('/')      
  ? ...
  : ...
```

This will fail on Windows because Windows uses `\` as a path separator, not `/`, and so path look like this in Windows
```sh
C:\Users\IEUser\Workspace\greenwood-getting-started\src\
```

as opposed to this on Linux / macOS
```sh
/Users/owenbuckley/Workspace/greenwood-getting-started/src
```

**Comment by thescientist13** [comment] 2021-05-19 22:50
Another update on this:
- While I was able to resolve issues with local development, it turned out there was another [issue related](https://github.com/alfredosalzillo/rollup-plugin-multi-input/issues/49) one of the Rollup plugins we use.  
- I created [a PR in Greenwood](https://github.com/ProjectEvergreen/greenwood/pull/609) to track all the WIP around this 

But with all those pieces working and [patched locally](https://github.com/thescientist13/rollup-multi-input-windows), I can confirm Greenwood is working great on Windows!  🎉 
![greenwood-serve-windows](https://user-images.githubusercontent.com/895923/118894809-f223af80-b8d2-11eb-86a5-cdba9d5fab65.png)

Mainly just need to get my fix upstreamed and then everything should be good to go!  🤞

**Closed** 2021-05-27 16:37 UTC
Labels: CLI, P0, bug, v0.12.3

**Comment by thescientist13** [comment] 2021-05-27 17:22
Hey @anlexN 

Just wanted to let you know that the **greenwood-getting-started** repo has been updated with this fix now, so if you want to upgrade / update your local version and make sure you are have v0.12.3 of Greenwood installed, you should be able to build now.
```sh
$ npm ls @greenwood/cli
greenwood-getting-started@1.0.0 /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood-getting-started
└── @greenwood/cli@0.12.3
```

Thanks again for helping us identify this fix.  🙏
